---
- name: FULL Kong Deletion (Kong ONLY – No PostgreSQL)
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Confirm FULL Kong deletion
      assert:
        that:
          - confirm_delete == "YES"
        fail_msg: "Deletion aborted. Type YES to confirm FULL Kong deletion."

  tasks:
    - name: Stop Kong service if present
      service:
        name: kong
        state: stopped
      ignore_errors: true

    - name: Disable Kong service if present
      service:
        name: kong
        enabled: false
      ignore_errors: true

    - name: Remove Kong package
      apt:
        name: kong
        state: absent
        purge: true
      ignore_errors: true

    - name: Remove Kong binary (custom installs)
      file:
        path: /usr/local/bin/kong
        state: absent

    - name: Remove Kong binary (apt installs)
      file:
        path: /usr/bin/kong
        state: absent

    - name: Remove Kong configuration directory
      file:
        path: /etc/kong
        state: absent

    - name: Remove Kong plugins directory
      file:
        path: /usr/local/share/lua/5.1/kong/plugins
        state: absent

    - name: Remove Kong logs directory
      file:
        path: /usr/local/kong
        state: absent

  post_tasks:
    - name: Kong deletion success message
      debug:
        msg: "✅ Kong has been fully removed from this host."
