---
- name: FULL Kong Deletion (Kong ONLY – No PostgreSQL)
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Confirm FULL Kong deletion
      assert:
        that:
          - confirm_delete == "YES"
        fail_msg: "Deletion aborted. Type YES to confirm FULL Kong deletion."

    - name: Check if Kong binary exists
      stat:
        path: /usr/local/bin/kong
      register: kong_bin

  tasks:
    - name: Stop Kong service
      service:
        name: kong
        state: stopped
      when: kong_bin.stat.exists

    - name: Disable Kong service
      service:
        name: kong
        enabled: false
      when: kong_bin.stat.exists

    - name: Remove Kong package
      apt:
        name: kong
        state: absent
        purge: true
      when: kong_bin.stat.exists

    - name: Remove Kong configuration directory
      file:
        path: /etc/kong
        state: absent

    - name: Remove Kong plugins directory
      file:
        path: /usr/local/share/lua/5.1/kong/plugins
        state: absent

    - name: Remove Kong logs directory
      file:
        path: /usr/local/kong
        state: absent

  post_tasks:
    - name: Kong deletion success message
      debug:
        msg: "✅ Kong has been successfully deleted from this host."
      when: kong_bin.stat.exists
